// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlLwvVPwd8-WW-KLef4uCkc6mQCjOPLLk',
    appId: '1:415934890151:web:ebe745ca48348bda6a9b82',
    messagingSenderId: '415934890151',
    projectId: 'gemapp-42f94',
    authDomain: 'gemapp-42f94.firebaseapp.com',
    storageBucket: 'gemapp-42f94.appspot.com',
    measurementId: 'G-K93KBJFR6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMt8CFYL5vHRy8pCWcv09GjUUnbuXdT0U',
    appId: '1:415934890151:android:9360bbf4fb5d30646a9b82',
    messagingSenderId: '415934890151',
    projectId: 'gemapp-42f94',
    storageBucket: 'gemapp-42f94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARygODcmXkndxxcXfsMb8P7Gl0QAZdyAU',
    appId: '1:415934890151:ios:ee3100a0589098fd6a9b82',
    messagingSenderId: '415934890151',
    projectId: 'gemapp-42f94',
    storageBucket: 'gemapp-42f94.appspot.com',
    iosBundleId: 'com.example.gemApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARygODcmXkndxxcXfsMb8P7Gl0QAZdyAU',
    appId: '1:415934890151:ios:8183191306db1c3e6a9b82',
    messagingSenderId: '415934890151',
    projectId: 'gemapp-42f94',
    storageBucket: 'gemapp-42f94.appspot.com',
    iosBundleId: 'com.example.gemApp2.RunnerTests',
  );
}
